parameters:
    canal_tp_scrum_board_it.issues_search.form.class: CanalTP\ScrumBoardItBundle\Form\Type\IssuesSearchType

services:

    canaltp_jira.rest:
        class: CanalTP\ScrumBoardItBundle\Jira\User\JiraRest
        arguments:
            - '%jira_url%'
    canaltp_jira_auth.user_provider:
        class: CanalTP\ScrumBoardItBundle\Jira\User\JiraUserProvider
        arguments:
            - @canaltp_jira.rest
#            - @service_container
    canaltp_jira_auth.authentication_success_handler:
        class: CanalTP\ScrumBoardItBundle\Security\Authentification\Handler\JiraAuthenticationHandler

    canaltp_jira_auth.authentication_failure_handler:
        class: CanalTP\ScrumBoardItBundle\Security\Authentification\Handler\JiraAuthenticationHandler

    canaltp_jira_auth.authentication_provider:
        class: CanalTP\ScrumBoardItBundle\Security\Authentification\Provider\JiraAuthProvider
        arguments: [@canaltp_jira_auth.user_provider, '', @canaltp_jira.rest]

    canaltp_jira_auth.authentication_listener:
        class: CanalTP\ScrumBoardItBundle\Security\Firewall\JiraListener
        arguments:
            - @security.context
            - @security.authentication.manager
            - @security.authentication.session_strategy
            - @security.http_utils
            - ''
            - @canaltp_jira_auth.authentication_success_handler
            - @canaltp_jira_auth.authentication_failure_handler
            - ''
            - @logger
            - @event_dispatcher
    canal_tp_scrum_board_it.service.manager:
        class: CanalTP\ScrumBoardItBundle\Service\ServiceManager
        arguments: [@service_container]
        calls:
            - [setServiceName, [%issues_service%]]
    canal_tp_scrum_board_it.jira.service:
        class: CanalTP\ScrumBoardItBundle\Service\JiraService
        arguments: [@security.context]
        calls:
            - [setOptions, [%jira%]]

    canal_tp_scrum_board_it.issues_search.form:
        class: %canal_tp_scrum_board_it.issues_search.form.class%
        arguments: [@canal_tp_scrum_board_it.service.manager]
        tags:
            - { name: form.type, alias: issues_search }
