# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - main_authenticator
                    - visitor_authenticator
                    - jira_authenticator
                    - github_authenticator
                entry_point: main_authenticator
            logout:
                path: /logout
                target: /
            remember_me:
                secret:   '%secret%'
            oauth:
                resource_owners:
                    github:          "/login/check-github"
                    jira:           "/login/check-jira"
                login_path:        /bugtracker
                use_forward:       false
                failure_path:      /bugtracker
                oauth_user_provider:
                    service: hwi_oauth.user.provider

    providers:
        webservice:
            id: user_provider

    encoders:
        ScrumBoardItBundle\Entity\User: bcrypt
    
    access_denied_url: /home