service: scrumboardit-server

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    SERVICE_NAME: ${self:service}

# you can overwrite defaults here
#  stage: dev
region: eu-central-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  boardsAll:
    handler: boards.all
    events:
      - http:
          path: boards
          method: get

#    Define function environment variables here
#    environment:
#      variable2: value2

plugins:
  - serverless-plugin-optimize

package:
  individually: true

custom:
  optimize:
    presets: ['flow']

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
