services:
    webservice_user_provider:
        class: ScrumBoardItBundle\Security\User\WebServiceUserProvider
    jira_token_authenticator:
        class: ScrumBoardItBundle\Security\JiraAuthenticator
        arguments: ['@router','%jira%','@security.rememberme.response_listener']
    jira.api:
<<<<<<< HEAD
        class: ScrumBoardItBundle\Services\ApiJira
=======
        class: ScrumBoardItBundle\API\ApiJira
>>>>>>> brieuc/post-it-manager
        arguments: ['@security.token_storage', '%jira%']
            
#    jira.rest:
#        class: ScrumBoardItBundle\Jira\User\JiraRest
#        arguments:
#            - '%jira_url%'
            
#    jira_auth.user_provider:
#        class: ScrumBoardItBundle\Jira\User\JiraUserProvider
#        arguments: ['@jira.rest']
