services:
   user.provider:
       class: ScrumBoardItBundle\Security\User\UserProvider
       arguments:
           - '@doctrine.orm.entity_manager'
           - '@session'
   main.authenticator:
       class: ScrumBoardItBundle\Security\MainAuthenticator
       arguments:
           - '@router'
           - '@security.encoder_factory'
   visitor.authenticator:
       class: ScrumBoardItBundle\Security\VisitorAuthenticator
       arguments:
           - '@router'
   jira.authenticator:
       class: ScrumBoardItBundle\Security\JiraAuthenticator
       arguments:
           - '@router'
           - '@api.caller'
           - '@security.token_storage'
           - '@session'
   github.authenticator:
       class: ScrumBoardItBundle\Security\GitHubAuthenticator
       arguments:
           - '@router'
           - '@api.caller'
           - '@security.token_storage'
           -
              host: https://api.github.com/
   discover.api:
       class: ScrumBoardItBundle\Services\Api\ApiVisitor
       arguments:
           - '@session'
           - '@security.token_storage'
   api.caller:
       class: ScrumBoardItBundle\Services\ApiCaller
   jira.api:
       class: ScrumBoardItBundle\Services\Api\ApiJira
       arguments:
           - '@security.token_storage'
           - '@session'
           - '@api.caller'
   github.api:
       class: ScrumBoardItBundle\Services\Api\ApiGithub
       arguments:
           - '@security.token_storage'
           -
              host: https://api.github.com/
           - '@api.caller'
           - '@doctrine.orm.entity_manager'
   general.persist:
     class: ScrumBoardItBundle\Services\Persist\General
     arguments:
           - '@security.token_storage'
           - '@doctrine.orm.entity_manager'
           - '@security.encoder_factory'
   jira_configuration.persist:
     class: ScrumBoardItBundle\Services\Persist\JiraConfiguration
     arguments:
           - '@security.token_storage'
           - '@doctrine.orm.entity_manager'
   favorites.persist:
     class: ScrumBoardItBundle\Services\Persist\Favorites
     arguments:
           - '@security.token_storage'
           - '@doctrine.orm.entity_manager'
           - '@session'
   profile.provider:
     class: ScrumBoardItBundle\Services\ProfileProvider
     arguments:
           - '@session'
           - '@form.factory'
           - 
              general: '@general.persist'
              jira_configuration: '@jira_configuration.persist'
              favorites: '@favorites.persist'