services:
    jira.rest:
        class: ScrumBoardItBundle\Jira\User\JiraRest
        arguments:
            - '%jira_url%'
            
    jira_auth.user_provider:
        class: ScrumBoardItBundle\Jira\User\JiraUserProvider
        arguments: ['@jira.rest']
            
    app.webservice_user_provider:
        class: ScrumBoardItBundle\Security\User\WebServiceUserProvider